### ISSUE TITLE
HAP_rand or HAPPlatformRandomNumberFill?

### ISSUE THREAD

**Issue by rojer** [apple/HomeKitADK#16]
Both fill a buffer with cryptographically secure random numbers, so why have both?
Wouldn't having just one be sufficient?

**Comment by aajain-com** [comment]
@rojer You are right, we could potentially replace `HAP_rand` with `HAPPlatformRandomNumberFill`

**Comment by Clovel** [comment]
Watch out, `HAP_rand` is referenced in the documentation here : https://github.com/apple/HomeKitADK/blob/master/Documentation/PAL.md. Maybe it is used on purpose ?

**Comment by pgravel-com** [comment]
HAPPlatformRandomNumberFill is the proper PAL API to use to generate a random number.

HAP_rand is probably better thought of as an internal API used by some platforms.
Currently HAP_rand is only used by Darwin's HAPPlatformRandomNumberFill implementation to make use of the supported crypto libraries's (ex: OpenSSL and MbedTLS) built-in random number generator, and by the MbedTLS wrapper using it's own rng function rather than going back to the PAL's HAPPlatformRandomNumberFill.

**Comment by rojer** [comment]
but in turn, mbedtls implementation uses arc4random_buf, which is not part of mbedtls.
imo HAP_rand should be eliminated. if arc4random_buf is good enough on darwin, then HAPPlatformRandomNumberFill should just use that.
i ran into this problem when porting to a platform that has mbedtls but not arc4random

**Comment by pgravel-com** [comment]
HAP_rand allows Darwin to use either OpenSSL and MbedTLS as crypto backends.

With that said, this really was just a convenient shortcut. If Darwin didn't rely on the crypto backend to provide the RNG, HAP_rand wouldn't need to exist. Could probably make Darwin behave the same as the POSIX PAL and remove HAP_rand.
