### ISSUE TITLE
two different lightbulbs one controller 

### ISSUE THREAD

**Issue by Asteliks** [apple/HomeKitADK#62]
Can I have two different lightbulbs controlled with one controller using HAP? How can I implement that? Could we have more examples besides the lightbulb and the lock?

**Comment by AustinRobinson** [comment]
I would also find this helpful.

**Comment by baysinger** [comment]
I think what you need is a bridge accessory, and an example of that is sorely missing from this repo.

See this closed issue: https://github.com/apple/HomeKitADK/issues/32

Basically, you define a new accessory for the bridge, and then you call HAPAccessoryServerStartBridge() instead of HAPAccessoryServerStart(), passing the bridge accessory and a list of the bridged accessories (the two lightbulbs). But definitely see the issue linked above for more details.

**Comment by Asteliks** [comment]
I have manager to implement it for the ESP32. This might be helpful
[https://github.com/Asteliks/AppleHomeKitADK-ESP32/tree/master/BridgeTwoLightbulbs/main](url)

**Comment by Asteliks** [comment]
Closing the issue as I have solved my problem
